
version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: transport_db
    volumes:
      - mongodb_data:/data/db

  passenger-service:
    build: ./passenger-service
    ports:
      - '8081:8081'
    environment:
      KAFKA_BROKER: kafka:29092
      MONGODB_URI: mongodb://admin:password@mongodb:27017
    depends_on:
      - kafka
      - mongodb

  transport-service:
    build: ./transport-service
    ports:
      - '8082:8082'
    environment:
      KAFKA_BROKER: kafka:29092
      MONGODB_URI: mongodb://admin:password@mongodb:27017
    depends_on:
      - kafka
      - mongodb

  ticketing-service:
    build: ./ticketing-service
    ports:
      - '8083:8083'
    environment:
      KAFKA_BROKER: kafka:29092
      MONGODB_URI: mongodb://admin:password@mongodb:27017
    depends_on:
      - kafka
      - mongodb

  payment-service:
    build: ./payment-service
    ports:
      - '8084:8084'
    environment:
      KAFKA_BROKER: kafka:29092
    depends_on:
      - kafka

  notification-service:
    build: ./notification-service
    ports:
      - '8085:8085'
    environment:
      KAFKA_BROKER: kafka:29092
    depends_on:
      - kafka

  admin-service:
    build: ./admin-service
    ports:
      - '8086:8086'
    environment:
      KAFKA_BROKER: kafka:29092
      MONGODB_URI: mongodb://admin:password@mongodb:27017
    depends_on:
      - kafka
      - mongodb

volumes:
  mongodb_data:
